// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// Manually maintained stub until protoc is run.
// source: proto/orchestrator/orchestrator.proto

package orchestrator

import (
	"context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// OrchestratorServiceClient is the client API for OrchestratorService.
type OrchestratorServiceClient interface {
	StartScan(ctx context.Context, in *StartScanRequest, opts ...grpc.CallOption) (*StartScanResponse, error)
	StopScan(ctx context.Context, in *StopScanRequest, opts ...grpc.CallOption) (*StopScanResponse, error)
	ScanStatus(ctx context.Context, in *ScanStatusRequest, opts ...grpc.CallOption) (*ScanStatusResponse, error)
}

type orchestratorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrchestratorServiceClient(cc grpc.ClientConnInterface) OrchestratorServiceClient {
	return &orchestratorServiceClient{cc}
}

func (c *orchestratorServiceClient) StartScan(ctx context.Context, in *StartScanRequest, opts ...grpc.CallOption) (*StartScanResponse, error) {
	out := new(StartScanResponse)
	err := c.cc.Invoke(ctx, "/orchestrator.OrchestratorService/StartScan", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorServiceClient) StopScan(ctx context.Context, in *StopScanRequest, opts ...grpc.CallOption) (*StopScanResponse, error) {
	out := new(StopScanResponse)
	err := c.cc.Invoke(ctx, "/orchestrator.OrchestratorService/StopScan", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorServiceClient) ScanStatus(ctx context.Context, in *ScanStatusRequest, opts ...grpc.CallOption) (*ScanStatusResponse, error) {
	out := new(ScanStatusResponse)
	err := c.cc.Invoke(ctx, "/orchestrator.OrchestratorService/ScanStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrchestratorServiceServer is the server API for OrchestratorService.
type OrchestratorServiceServer interface {
	StartScan(context.Context, *StartScanRequest) (*StartScanResponse, error)
	StopScan(context.Context, *StopScanRequest) (*StopScanResponse, error)
	ScanStatus(context.Context, *ScanStatusRequest) (*ScanStatusResponse, error)
	mustEmbedUnimplementedOrchestratorServiceServer()
}

// UnimplementedOrchestratorServiceServer should be embedded for forward compatibility.
type UnimplementedOrchestratorServiceServer struct{}

func (UnimplementedOrchestratorServiceServer) StartScan(context.Context, *StartScanRequest) (*StartScanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartScan not implemented")
}
func (UnimplementedOrchestratorServiceServer) StopScan(context.Context, *StopScanRequest) (*StopScanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopScan not implemented")
}
func (UnimplementedOrchestratorServiceServer) ScanStatus(context.Context, *ScanStatusRequest) (*ScanStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ScanStatus not implemented")
}
func (UnimplementedOrchestratorServiceServer) mustEmbedUnimplementedOrchestratorServiceServer() {}

// UnsafeOrchestratorServiceServer may be embedded for disabling forward-compatibility.
type UnsafeOrchestratorServiceServer interface {
	mustEmbedUnimplementedOrchestratorServiceServer()
}

func RegisterOrchestratorServiceServer(s grpc.ServiceRegistrar, srv OrchestratorServiceServer) {
	s.RegisterService(&OrchestratorService_ServiceDesc, srv)
}

var OrchestratorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "orchestrator.OrchestratorService",
	HandlerType: (*OrchestratorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartScan",
			Handler:    _OrchestratorService_StartScan_Handler,
		},
		{
			MethodName: "StopScan",
			Handler:    _OrchestratorService_StopScan_Handler,
		},
		{
			MethodName: "ScanStatus",
			Handler:    _OrchestratorService_ScanStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/orchestrator/orchestrator.proto",
}

func _OrchestratorService_StartScan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartScanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServiceServer).StartScan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/orchestrator.OrchestratorService/StartScan"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServiceServer).StartScan(ctx, req.(*StartScanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorService_StopScan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopScanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServiceServer).StopScan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/orchestrator.OrchestratorService/StopScan"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServiceServer).StopScan(ctx, req.(*StopScanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorService_ScanStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScanStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServiceServer).ScanStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/orchestrator.OrchestratorService/ScanStatus"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServiceServer).ScanStatus(ctx, req.(*ScanStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}
